### ISSUE TITLE
changed keyboard layout does not survive unplug/plug keyboard

### ISSUE THREAD

**Issue by beta-tester** [raspberrypi/rc_gui#12]
i changed the keyboard layout in raspbian jessie to de-DE via isung the rc_gui.
if i unplug and plug again my usb-keyboard, the settings switch back to en-UK immediately.
any idea, how to fix that, to have permanent the de-DE settings, that survive a re-plug (unplug/plug) keyboard?

**Comment by beta-tester** [comment]
posted by wardjk:
I have the same problem as beta-tester. In my specific case, I use a KVM switch to connect to the RPi. The selected language doesn't matter. Upon reconnecting the keyboard to the RPi, keyboard layout setting goes back to "United Kingdom - English (UK)".

**Comment by Mnemocron** [comment]
I'm having the same issue on my Raspberry Pi B runnig Jessie (4.1.13+) when changing it to German (Switzerland). Keyboard: Logitech K120

**Comment by spl237** [comment]
This is unfortunately a "feature" of the international keyboard driver we are using - it doesn't support hot-plugging of keyboards. Unless the driver authors decide to support hot-plug, or we find a better international solution, this is probably not fixable in the short to medium term.

**Comment by mamert** [comment]
OK, OK, but is there a working workaround? Not everyone uses UK layout, you know, so this is a pain.

**Comment by spl237** [comment]
Not to my knowledge. For the time being, the answer is that the Raspbian desktop does not support hotplugging of keyboards. We'll probably get around to looking at it at some point, but it's not a priority, so I can't say when.

You could try setting the keyboard in the command-line version of raspi-config, which uses a different method to set the keyboard - no idea if that will work, but probably worth a try.

I believe the keyboard internationalisation utility we use (lxkeymap) is also used in Ubuntu, so this may have been fixed in other versions of Linux.

**Comment by mamert** [comment]
OK, for my purposes `sudo leafpad /etc/default/keyboard` and setting XKBLAYOUT to "pl" did the trick, it persists.

**Comment by matoken** [comment]
It is a method in the debian.
```
$ sudo dpkg-reconfigure keyboard-configuration
```
It is a method in the debian.
```
$ sudo dpkg-reconfigure keyboard-configuration
```
